apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-todo-app
  template:
    metadata:
      labels:
        app: nodejs-todo-app
    spec:
      containers:
      - name: nodejs-todo-app
        image: dirudeen/nodejs-todo-app-image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000