apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nodejs-todo-app
  ports:
    name: http
    port: 80 
    targetPort: 3000
    protocol: TCP
